### ISSUE TITLE
Error compiling project

### ISSUE THREAD

**Issue by ottopic** [lambus-platform/titanium-notification-banner#1]
Hello @hansemannn ,
I'm trying to compile your project to use titanium-notification-banner but I get error and I don't understand how to fix it. Can you help me?

appc run -p ios --build-only

Appcelerator Command-Line Interface, version 7.0.12
Copyright (c) 2014-2019, Appcelerator, Inc.  All Rights Reserved.

2019-6-26 13:43:44

Operating System
  Name                        = Mac OS X
  Version                     = 10.14.5
  Architecture                = 64bit
  # CPUs                      = 8
  Memory                      = 17179869184

Node.js
  Node.js Version             = 8.9.1
  npm Version                 = 5.5.1

Titanium CLI
  CLI Version                 = 5.1.1

Titanium SDK
  SDK Version                 = 8.0.2.GA
  SDK Path                    = /Users/myuseraccount/Library/Application Support/Titanium/mobilesdk/osx/8.0.2.GA
  Target Platform             = iphone

Command
  /usr/local/bin/node /Users/myuseraccount/.appcelerator/install/7.0.12/package/node_modules/titanium/lib/titanium.js build -p ios --build-only --config-file /var/folders/1r/qvzpb99n7wv83_z512zwdfyc0000gp/T/build-1561549420715.json --log-level info --no-banner --project-dir /Users/myuseraccount/Downloads/titanium-notification-banner-master/ios

[INFO]  Project directory: /Users/myuseraccount/Downloads/titanium-notification-banner-master/ios
[INFO]  Module ID: ti.notificationbanner
[INFO]  Module Type: Framework (Swift)
[ERROR] [xcode-sim] ** BUILD FAILED **
[ERROR] [xcode-sim] The following build commands failed:
[ERROR] [xcode-sim] 	CompileSwift normal i386 /Users/myuseraccount/Downloads/titanium-notification-banner-master/ios/Classes/TiNotificationbannerModule.swift
[ERROR] [xcode-sim] 	CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
[ERROR] [xcode-sim] 	CompileSwift normal x86_64 /Users/myuseraccount/Downloads/titanium-notification-banner-master/ios/Classes/TiNotificationbannerModule.swift
[ERROR] [xcode-sim] 	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
[ERROR] [xcode-sim] (4 failures)

**Comment by ottopic** [comment]
Solved compiling with 8.1.0

**Comment by PietroGranati** [comment]
I cannot resolve with your resolution

**Comment by ottopic** [comment]
Yes, I'm try to build it again but I get that error:

`
[ERROR] [xcode-sim] ** BUILD FAILED **
[ERROR] [xcode-sim] The following build commands failed:
[ERROR] [xcode-sim] 	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
[ERROR] [xcode-sim] 	CompileSwift normal x86_64 /Users/user/Downloads/titanium-notification-banner-master/ios/Classes/TiNotificationbannerModule.swift
[ERROR] [xcode-sim] (2 failures)
`

@hansemannn can you help us?

**Comment by ottopic** [comment]
I think the problem is my Xcode version 11.3.1 with last Swift version. To build module is required Swift 5.

**Comment by hansemannn** [comment]
You need to recompile the native library with your swift version
