### ISSUE TITLE
Support for TiSDK 10+ / iOS 15

### ISSUE THREAD

**Issue by designbymind** [lambus-platform/titanium-notification-banner#12]
Hey Hans,

I've attempted to build the module on my machine, however, I'm running into a few build errors whilst compiling the module...

**Question:** Do you have a version supporting **iOS 15**, targeting TiSDK 10+ (latest `10.1.0.GA`)?

Thank you for the awesome module, I'd love to begin using it!

· Jason

**Comment by hansemannn** [comment]
Should work fine with the latest version :)
